### ISSUE TITLE
source of data question

### ISSUE THREAD

**Issue by epogrebnyak** [nassarhuda/MIT18.S191-graphslecture#1]
For this repo the data is given as csv files? Or there is a scapper code to generate twitter dataset and julia dataset?

Could be a good addition to explain this in README.md, if you got time for this.

**Comment by epogrebnyak** [comment]
I should probably add students will love to scrapp something themselves.

**Comment by epogrebnyak** [comment]
Oh, from video for twitter I understand the scrapping is via `twint`. What about data julia packages data?

Does [this](https://github.com/nassarhuda/MIT18.S191-graphslecture/blob/899024e4fbd7585348bd38f76bb1260adcb2b6b0/Julia-dependency-graph/Julia-dependency-graph.jl#L11-L12) mean you collect package dependence from stlib (not all of Julia packages)?

**Comment by epogrebnyak** [comment]
You seem to rely on [registry.toml](https://github.com/JuliaRegistries/General/blob/master/Registry.toml) to get package UUIDs, right - but what is the source of dependecies for each package?

**Comment by epogrebnyak** [comment]
I'm findng this now:

- code for twitter: https://github.com/nassarhuda/MIT18.S191-graphslecture/blob/master/part3_fun_networks/generate_graph.jl
- code for julia: https://github.com/nassarhuda/MIT18.S191-graphslecture/blob/master/Julia-dependency-graph/Julia-dependency-graph.jl

Different places, but more clear now.

**Comment by nassarhuda** [comment]
Hello!

Yes, you got those right. The package dependency graph is originally from here: https://github.com/dgleich/more-graphs/tree/master/Julia-dependency-graph

And to regenerate the twitter graph: https://github.com/nassarhuda/MIT18.S191-graphslecture/blob/master/part3_fun_networks/generate_graph.jl (though you only need to re run steps 2 and 4).
